#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define UP_ARROW 72
#define DOWN_ARROW 80
#define LEFT_ARROW 75
#define RIGHT_ARROW 77
#define UP_BORDER 7
#define DOWN_BORDER 0
#define LEFT_BORDER 0
#define RIGHT_BORDER 7
#define LETTER 65
#define BOARD_SIZE 8
#define CURRENT_EMPTY_SQUARE 176
#define LEFT_TOP_EDGE 195
#define TOP_EDGE 196
#define RIGHT_TOP_EDGE 180
#define LEFT_EDGE 124
#define RIGHT_EDGE 124

#endif